name: Mission-Item
main: com.rrayy.msit.msit
version: 1.0
author: rrayy
description: mission item plugin
website: https://chzzk.naver.com/64d76089fba26b180d9c9e48a32600d9
api-version: '1.21'
loader: com.rrayy.msit.Loader
dependencies:
  bootstrap:
    - name: SomeBootstrapDependency
      load: BEFORE
      required: true
      join-classpath: true
  server:
    - name: SomeServerDependency
      load: AFTER
      required: true
      join-classpath: false